version: "3.8"
    
services:

    flask-app:
        container_name: flask-app
        build: .
        ports:
          - target: 5500
        env_file: .env
            
    nginx:
        image: nginx:latest
        ports:
          - target: 80
            published: 80
        volumes:
          - type: bind
            source: ./nginx.conf
            target: /etc/nginx/nginx.conf
